### ISSUE TITLE
Thanks for sharing your code

### ISSUE THREAD

**Issue by Quiqui64** [ogiewon/Hubitat#15]
Thank you for every thing you have done on Hubitat and Smartthings.
Do mine if i use some your code I've been looking for a example of a debounce, which you have here.

Thank you again,

Jason

**Comment by ogiewon** [comment]
Sure, you can use it. I am curious about the debounce code in particular. What code are you referring to?

**Comment by Quiqui64** [comment]
I'm talking about the debounce you have in this driver https://github.com/ogiewon/Hubitat/tree/master/Drivers/aeon-hem-v1-laundry.src

I have a esp8266 controlling my Hampton Bay  fan with a RF transmitter using this arduino library https://github.com/crankyoldgit/IRremoteESP8266 .

The problem I'm having is integrating it with homebridge, when changing the fan speed in the Apple Home app for example, from "off" to "hi" the app sends out the "low" command, then "medium" command, then the "High" command in a very fast succession. Which intern my driver sends the commands to the esp8266 to send the http commands. I want my driver just to send the "high" command.

Hope that was not to confusing.

Thanks,

Jason

**Comment by ogiewon** [comment]
Makes perfect sense to me!  Feel free to use whatever you'd like from that driver.  It started its life over on SmartThings and was written by Mike Maxwell.  I ported it to Hubitat and am still using it 1.5 years later without any issues.  A few other users asked for some enhancements, including the debounce logic with I added.  

Have fun!
Dan
