### ISSUE TITLE
Hue API transitions

### ISSUE THREAD

**Issue by xxKeoxx** [ogiewon/Hubitat#16]
HAve you tried to use this driver with the HUE API?  I am trying to use transitiontime with my scenes, but it doesn't seem to use the transition time.
/api/{whitelistuser}/groups/8/action
{"scene": "l71FiNzz1NkCQ-d", "transitiontime": "40"}

Have you gotten this to work?

**Comment by ogiewon** [comment]
No, I have not tried to use the HTTP Momentary Driver with Hue.  I do not have a Hue bridge, so I cannot even try it.

**Comment by ogiewon** [comment]
This is more of a question for the Hubitat Community Forums, as opposed to a GitHub Issue.  Therefore, I am closing this issue.
