### ISSUE TITLE
Channel Numbers

### ISSUE THREAD

**Issue by ghost** [ogiewon/Hubitat#31]
Thank you for this driver. I've made a small modification that I am using that allows the direct use of channel numbers for the current Activity. I was wondering if you're interested or would rather keep it out?

**Comment by ogiewon** [comment]
I am definitely willing to consider it, so long as it doesn't overly complicate the Parent Device code.

**Comment by ghost** [comment]
I think I've corrected created a Pull request, I've not used GitHub in anger much.

**Comment by ogiewon** [comment]
Thank you.  I have merged your pull request.
