### ISSUE TITLE
Cannot toggle DEBUG or TEXT Logging

### ISSUE THREAD

**Issue by LibraSun** [ogiewon/Hubitat#35]
Noticed I'm getting tons of extraneous Log activity in connection with this app, whenever a Pushover message gets sent.
Rather than manually comment out all the lines where this driver code logs actions, I'd like to simply ask that users be afforded the traditional "Debug?" and "Text logging?" toggles on the app/child Preference page.
THANKS! Otherwise loving the app very much, and appreciate all your effort.
 - LibraSun

**Comment by ogiewon** [comment]
Done!  Simply open up the custom driver on your hub, and click IMPORT near the top.  Allow it to overwrite the existing code and then click save.  Next, go to each Pushover device, configure the new debug logging setting, and click SAVE.

**Comment by LibraSun** [comment]
Yay, worked! U da man. Proper thanks would have to wait until Friday when they re-admit me to the Forum after an unexpected week-long Suspension, LOL. Hope I can return the favor one day. 
- LS
